cmake_minimum_required(VERSION 3.22)
project(samsung_oboe)
find_package(oboe REQUIRED CONFIG)
add_library(samsung_oboe SHARED oboe_sink.cpp atomic_builtin.c)
target_compile_features(samsung_oboe PRIVATE cxx_std_17)
target_compile_options(samsung_oboe PRIVATE -O3 -fvisibility=hidden -fomit-frame-pointer -mno-outline-atomics)
target_link_libraries(samsung_oboe oboe::oboe android log)
